export interface AvoidableAbility {
  name: string;
  note?: string;
  nonTankOnly?: boolean;
}

export const AVOIDABLE_ABILITIES: Record<number, AvoidableAbility> = {
  720: { name: 'Ice Spike' },
  1416: { name: 'Poisonado', note: 'It better to Crowd Control this ability cast than to kite.' }, // TODO: Maybe 1649?
  737: { name: 'Slicing Blades' },
  724: { name: 'Rapid Fire' },
  1819: { name: 'Shattering Ice' },
  748: { name: 'Razor Trap' },
  747: { name: 'Cold Blooded Twist' },
  203: { name: 'Flame Blast' },
  205: { name: 'Glacial Sunder' },
  279: { name: 'Eye Of Ulmorgat' },
  830: { name: 'Armaggedon' },
  59: { name: 'Grip', note: 'Stay closer than 15m of the Mancatchers' },
  546: { name: 'Salted Blade', note: 'Stack in melee' },
  275: { name: 'Backstab', note: 'Reposition to not give your back to Nightmist Cutthroat' },
  527: { name: 'Sunken Gale' },
  535: { name: 'Rupture Earth' },
  57: { name: 'Bombs Away!' },
  599: { name: 'Wavestomp' },
  806: { name: 'Acidic Sap' },
  793: { name: 'Dunehunters Trap' },
  794: { name: 'Soulpiercer' },
  781: { name: 'Whirlwind' },
  785: { name: 'Crescent Cleave' },
  460: { name: 'Penumbra' },
  1664: { name: 'Sinnaris Judgement' },
  27: { name: 'Volley' },
  647: { name: 'Earthcore Upheaval' },
  301: { name: 'Mince' },
  1645: { name: 'Razorlace Web' },
  470: { name: 'Venom Spray' },
  616: { name: 'Ball Lightning' },
  1449: { name: 'Grasping Vines' },
  2179: { name: 'Bleeding' },
  710: { name: 'Howling Blast' },
  838: { name: 'Executioners Cleave', nonTankOnly: true, note: "Don't stand close to the tank" },
  534: { name: 'Anchor Strike', nonTankOnly: true, note: "Don't stand close to the tank" },
  592: { name: 'Anchor Strike', nonTankOnly: true, note: "Don't stand close to the tank" },
  56: { name: 'Dark Cleave', nonTankOnly: true, note: "Don't stand close to the tank" },
  784: { name: 'Attack', nonTankOnly: true, note: "Don't stand close to the tank" },
  458: { name: 'Lunar Soulsear', nonTankOnly: true, note: "Don't stand close to the tank" },
  492: { name: 'Wailing Strike', nonTankOnly: true, note: "Don't stand close to the tank" },
  1634: { name: 'Forked Lightning', nonTankOnly: true, note: "Don't stand close to the tank" },
};
